define([], function() {
  return {
    "DebugLayoutOption": "Debug",
    "FilterParameter": "$filter parameter value",
    "InvalidNumberIntervalMessage": "Value needs to be at least 1 and maximum 999",
    "NoResultMessage": "No results to display",
    "OrderByParameter": "$orderby parameter value",
    "PageSizeParameter": "Number of items per page",
    "PeopleLayoutOption": "People",
    "PlaceHolderEditLabel": "Edit",
    "PlaceHolderConfigureBtnLabel": "Configure",
    "PlaceHolderIconText": "People Search Web Part",
    "PlaceHolderDescription": "This component displays people search results from Microsoft Graph",
    "QuerySettingsGroupName": "Query",
    "ResultsLayoutLabel": "Results layout",
    "ResultsCount": "{0} results",
    "SearchInputPlaceholder": "Enter your search terms...",
    "SearchParameter": "$search parameter value",
    "SearchParameterOption": "$search parameter option",
    "NoneSearchParameterOption": "None",
    "StaticSearchParameterOption": "Static",
    "BoxSearchParameterOption": "Search box",
    "DynamicSearchParameterOption": "Dynamic data",
    "SearchQuerySettingsGroupName": "Search Parameter",
    "SelectParameter": "$select parameter value",
    "ShowPaginationControl": "Show pagination",
    "ShowLivePersonaCard": "Show Live Persona Card",
    "ShowResultsCountLabel": "Show results count",
    "HideResultsOnloadLabel": "Hide results on load (without a query)",
    "ShowBlankLabel": "Show blank if no result",
    "ShowBlankEditInfoMessage": "No result returned for this query. This Web Part will remain blank in display mode according to parameters.",
    "StylingSettingsGroupName": "Styling options",
    "EnableUmlautReplacement": "Enable umlaut replacement",
    "TemplateParameters": {
      "TemplateParametersGroupName": "Template options",
      "ManagePeopleFieldsLabel": "Manage persona fields",
      "ManagePeopleFieldsPanelDescriptionLabel": "Here you can map each field values with the corresponding persona placeholders.",
      "PlaceholderNameFieldLabel": "Name",
      "PlaceholderValueFieldLabel": "Value",
      "PlaceholderSearchableFieldLabel": "Searchable",
      "PersonaSizeOptionsLabel": "Picture size",
      "PersonaSizeExtraSmall": "Extra small",
      "PersonaSizeSmall": "Small",
      "PersonaSizeRegular": "Regular",
      "PersonaSizeLarge": "Large",
      "PersonaSizeExtraLarge": "Extra large",
    },
    "ShowBackgroundLabel": "Allow section background to be visible"
  }
});
